
export let database = [
    {
      id: 4,
      status: "A fazer",
      empresa: "COCALQUI",
      cliente: "Jonatas Fernandes",
      responsavel: "Jonatas Fernandes",
      nf: 6986,
      setor: "PCP",
      notaAvaliacao: "-",
      dataRequisicao: "03/01/2023",
      dataConclusao: "-",
    },
    {
      id: 3,
      status: "A fazer",
      empresa: "COCALQUI",
      cliente: "Israel Almeida",
      responsavel: "Tamares Lima",
      nf: 21241,
      setor: "PCP",
      notaAvaliacao: "-",
      dataRequisicao: "02/03/2023",
      dataConclusao: "-",
    },
    {
      id: 2,
      status: "em Andamento",
      empresa: "ANIGER",
      cliente: "Igor Martins",
      responsavel: "Julio Oliveira",
      nf: 325,
      setor: "Compras",
      notaAvaliacao: "-",
      dataRequisicao: "02/03/2023",
      dataConclusao: "-",
    },
    {
      id: 1,
      status: "Concluído",
      empresa: "ANIGER",
      cliente: "Fabiana Sousa",
      responsavel: "Amanda Amancio",
      nf: 102541,
      setor: "Transportes",
      notaAvaliacao: "5",
      dataRequisicao: "30/01/2023",
      dataConclusao: "01/02/2023",
    },
  ]